version: '3.1'
services:  
  eureka:
    image: eureka
    build: ./eureka
    container_name: eureka
    ports:
      - '8761'   

  client:
    image: client
    build: ./client
    container_name: client
    ports:
      - '5000'
    deploy:
      replicas: 4  


#docker stack deploy -c stack.yml docker-compose.yml
#docker stack deploy -c  docker-compose.yml deploy
#https://github.com/anokun7/docker-springframework