management:
  security:  
    enabled: false  
    
spring:
  application:
    name: eureka

server:
  port: 8761

eureka:
  instance:
    prefer-ip-address: true  
    leaseRenewalIntervalInSeconds: 3
    leaseExpirationDurationInSeconds: 3  
    ip-address: ${DOCKER_HOST_IP}
    metadataMap:
      instanceId: ${spring.application.name}:${server.port} 
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 5
  serviceUrl:
     defaultZone: ${EUREKA_URI:http://${DOCKER_HOST_IP:8761/eureka}

  
